# Generated by Django 5.1.7 on 2025-05-03 10:46

import commons.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "position",
                    commons.models.FloatPairField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
                (
                    "size",
                    commons.models.FloatPairField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
                ("rotation", models.FloatField()),
            ],
            options={
                "default_related_name": "visual_objects",
            },
        ),
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "size",
                    commons.models.FloatPairField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="venues.venue"
                    ),
                ),
            ],
            options={
                "default_related_name": "layouts",
                "unique_together": {("name", "venue")},
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "visualobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="layouts.visualobject",
                    ),
                ),
            ],
            options={
                "default_related_name": "seats",
            },
            bases=("layouts.visualobject",),
        ),
        migrations.AddField(
            model_name="visualobject",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="layouts.layout"
            ),
        ),
        migrations.AddField(
            model_name="visualobject",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="SeatZone",
            fields=[
                (
                    "seat_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="layouts.seat",
                    ),
                ),
                ("seat_amount", models.PositiveSmallIntegerField()),
            ],
            options={
                "default_related_name": "seat_zones",
            },
            bases=("layouts.seat",),
        ),
    ]
