# Generated by Django 5.1.7 on 2025-05-10 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layouts", "0002_layout_edited_at_layout_previous_version"),
        ("venues", "0003_venue_is_current"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="layout",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="layout",
            name="is_current",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddConstraint(
            model_name="layout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("name", "venue"),
                name="unique_current_layout_name",
            ),
        ),
    ]
