# Generated by Django 5.1.7 on 2025-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layouts", "0003_alter_layout_unique_together_layout_is_current_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="layout",
            name="unique_current_layout_name",
        ),
        migrations.RemoveField(
            model_name="layout",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="layout",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="layout",
            name="previous_version",
        ),
    ]
