# Generated by Django 5.1.7 on 2025-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layouts", "0004_remove_layout_edited_at_remove_layout_is_current_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layout",
            options={"default_related_name": "layouts", "ordering": ["name", "pk"]},
        ),
    ]
