# Generated by Django 5.1.7 on 2025-05-20 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reaction",
            options={"default_related_name": "reactions", "ordering": ["pk"]},
        ),
    ]
