# Generated by Django 5.1.7 on 2025-05-17 19:17

import commons.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_duration", models.DurationField()),
                ("is_current", models.BooleanField(blank=True, default=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "default_related_name": "schedules",
            },
        ),
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    commons.models.WeekDayField(
                        choices=[
                            (0, "monday"),
                            (1, "tuesday"),
                            (2, "wednesday"),
                            (3, "thursday"),
                            (4, "friday"),
                            (5, "saturday"),
                            (6, "sunday"),
                        ]
                    ),
                ),
                (
                    "work_hours",
                    commons.models.TimeRangeField(
                        base_field=models.TimeField(), size=2
                    ),
                ),
                (
                    "break_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=commons.models.TimeRangeField(
                            base_field=models.TimeField(), size=2
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "slots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TimeField(), size=None
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["week_day"],
                "default_related_name": "work_days",
            },
        ),
    ]
