# Generated by Django 5.1.7 on 2025-05-05 15:33

from django.db import migrations

import commons.models


def copy_data_to_week_day(apps, schema_editor):
    WorkDay = apps.get_model("schedules", "WorkDay")
    for obj in WorkDay.objects.all():
        obj.week_day = obj.day
        obj.save(update_fields=["week_day"])


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="week_day",
            field=commons.models.WeekDayField(
                choices=[
                    (0, "monday"),
                    (1, "tuesday"),
                    (2, "wednesday"),
                    (3, "thursday"),
                    (4, "friday"),
                    (5, "saturday"),
                    (6, "sunday"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(
            copy_data_to_week_day,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="workday",
            name="day",
        ),
        migrations.AlterField(
            model_name="workday",
            name="week_day",
            field=commons.models.WeekDayField(
                choices=[
                    (0, "monday"),
                    (1, "tuesday"),
                    (2, "wednesday"),
                    (3, "thursday"),
                    (4, "friday"),
                    (5, "saturday"),
                    (6, "sunday"),
                ],
            ),
        ),
    ]
