# Generated by Django 5.1.7 on 2025-05-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0002_rename_day_week_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="previous_version",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child",
                to="schedules.schedule",
            ),
        ),
    ]
