# Generated by Django 5.1.7 on 2025-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedules",
            "0002_remove_schedule_edited_at_remove_schedule_is_current_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"default_related_name": "schedules", "ordering": ["pk"]},
        ),
    ]
