# Generated by Django 5.1.7 on 2025-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0003_schedule_edited_at_schedule_previous_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_current",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
