# Generated by Django 5.1.7 on 2025-05-13 11:33

import django.contrib.postgres.fields
from django.db import migrations, models

from schedules.models import generate_slots


def add_slots(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")
    for schedule in Schedule.objects.all():
        booking_duration = schedule.booking_duration
        for work_day in schedule.work_days.all():
            work_hours = work_day.work_hours
            break_hours = getattr(work_day, "break_hours")
            if break_hours is None:
                break_hours = []

            work_day.slots = generate_slots(booking_duration, work_hours, break_hours)
            work_day.save(update_fields=["slots"])


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0004_schedule_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="slots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TimeField(), null=True, size=None
            ),
        ),
        migrations.RunPython(add_slots, migrations.RunPython.noop),
    ]
