# Generated by Django 5.1.7 on 2025-05-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_activity_location_activity_venue"),
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activities.recurringactivity",
            ),
        ),
    ]
