# Generated by Django 5.1.7 on 2025-05-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0002_alter_option_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="option",
            name="previous_version",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child",
                to="options.option",
            ),
        ),
    ]
