# Generated by Django 5.1.7 on 2025-05-10 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_activity_location_activity_venue"),
        ("options", "0003_option_edited_at_option_previous_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="option",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="option",
            name="is_current",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("name", "activity"),
                name="unique_current_option_per_activity",
            ),
        ),
    ]
