# Generated by Django 5.1.7 on 2025-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0004_alter_option_unique_together_option_is_current_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="option",
            name="unique_current_option_per_activity",
        ),
        migrations.RemoveField(
            model_name="option",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="option",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="option",
            name="previous_version",
        ),
    ]
