# Generated by Django 5.1.7 on 2025-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0005_remove_option_edited_at_remove_option_is_current_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"default_related_name": "options", "ordering": ["name", "pk"]},
        ),
    ]
