# Generated by Django 5.1.7 on 2025-05-07 15:57

import commons.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("options", "0002_alter_option_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "week_day",
                    commons.models.WeekDayField(
                        choices=[
                            (0, "monday"),
                            (1, "tuesday"),
                            (2, "wednesday"),
                            (3, "thursday"),
                            (4, "friday"),
                            (5, "saturday"),
                            (6, "sunday"),
                        ]
                    ),
                ),
                ("time", models.TimeField()),
                ("note", models.TextField(blank=True, default="")),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="options.option"
                    ),
                ),
            ],
            options={
                "default_related_name": "bookings",
            },
        ),
    ]
