# Generated by Django 5.1.7 on 2025-05-23 06:12

import commons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activities",
            "0004_alter_activity_options_alter_onetimeactivity_options_and_more",
        ),
        ("bookings", "0002_alter_booking_options"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("layouts", "0005_alter_layout_options"),
        ("options", "0006_alter_option_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="note",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="week_day",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="option",
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "default_related_name": "bookings",
                "ordering": ["booked_at", "activity", "pk"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="activities.activity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="OneTimeActivityBooking",
            fields=[
                (
                    "booking_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="layouts.seat"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "one_time_activity_bookings",
                "base_manager_name": "objects",
            },
            bases=("bookings.booking",),
        ),
        migrations.CreateModel(
            name="RecurringActivityBooking",
            fields=[
                (
                    "booking_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookings.booking",
                    ),
                ),
                (
                    "week_day",
                    commons.models.WeekDayField(
                        choices=[
                            (0, "monday"),
                            (1, "tuesday"),
                            (2, "wednesday"),
                            (3, "thursday"),
                            (4, "friday"),
                            (5, "saturday"),
                            (6, "sunday"),
                        ]
                    ),
                ),
                ("time", models.TimeField()),
                ("note", models.TextField(blank=True, default="")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="options.option"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "recurring_activity_bookings",
                "base_manager_name": "objects",
            },
            bases=("bookings.booking",),
        ),
    ]
