# Generated by Django 5.1.7 on 2025-05-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_remove_booking_note_remove_booking_week_day_and_more"),
        ("layouts", "0005_alter_layout_options"),
        ("options", "0006_alter_option_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimeactivitybooking",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="layouts.seat",
            ),
        ),
        migrations.AlterField(
            model_name="recurringactivitybooking",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="options.option",
            ),
        ),
    ]
