# Generated by Django 5.1.7 on 2025-06-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_alter_onetimeactivitybooking_seat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringactivitybooking",
            name="week_day",
        ),
        migrations.AddField(
            model_name="recurringactivitybooking",
            name="date",
            field=models.DateField(default="2024-02-08"),
            preserve_default=False,
        ),
    ]
