# Generated by Django 5.1.7 on 2025-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_venue_edited_at_venue_previous_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_current",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
