# Generated by Django 5.1.7 on 2025-05-20 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0004_remove_venue_edited_at_remove_venue_is_current_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name", "created_at", "pk"]},
        ),
    ]
