# Generated by Django 5.1.7 on 2025-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0005_alter_venue_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_published",
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
