# Generated by Django 5.1.7 on 2025-06-07 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0006_venue_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="website_links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, default=list, size=10
            ),
        ),
    ]
