# Generated by Django 5.1.7 on 2025-04-10 18:56

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        CreateExtension("postgis"),
        VectorExtension(),
        CreateExtension("pg_trgm"),
    ]
