# Generated by Django 5.1.7 on 2025-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="media",
            field=models.ManyToManyField(to="files.file"),
        ),
        migrations.DeleteModel(
            name="ActivityMedia",
        ),
    ]
