# Generated by Django 5.1.7 on 2025-05-20 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_activity_location_activity_venue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"default_related_name": "activities", "ordering": ["name", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="onetimeactivity",
            options={
                "base_manager_name": "objects",
                "default_related_name": "one_time_activities",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringactivity",
            options={
                "base_manager_name": "objects",
                "default_related_name": "recurring_activities",
            },
        ),
    ]
