# Generated by Django 5.1.7 on 2025-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "activities",
            "0004_alter_activity_options_alter_onetimeactivity_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_published",
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
