# Generated by Django 5.1.7 on 2025-05-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_activity_is_published"),
        ("schedules", "0003_alter_schedule_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringactivity",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="schedules.schedule",
            ),
        ),
    ]
