# Generated by Django 5.1.7 on 2025-05-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_alter_recurringactivity_schedule"),
        ("venues", "0006_venue_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="is_remote",
        ),
        migrations.AlterField(
            model_name="activity",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="venues.venue",
            ),
            preserve_default=False,
        ),
    ]
