# Generated by Django 5.1.7 on 2025-05-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_remove_activity_is_remote_alter_activity_venue"),
        ("layouts", "0005_alter_layout_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimeactivity",
            name="layout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="layouts.layout",
            ),
            preserve_default=False,
        ),
    ]
